### ISSUE TITLE
Legacy GPU option in ISO

### ISSUE THREAD

**Issue by KingDutchIsBad** [axyl-os/axyl-iso#13]
Hello there I have a request! 
 Currently It does not look like the ISO supports legacy GPUs and doesn't have a option to select the driver version either. This is really bad for some people like myself who cannot try out this distro. 
Is there anyway to implement this feature. A single option to pick a GPU driver version would work fine

**Comment by Kungger-git** [comment]
There is a blogpost about Legacy GPUs in XeroLinux website:
[https://xldb.techxero.com/blog/30-nvidia-kepler-series-cards-are-now-legacy](url)

There are 2 solutions, this came from the blogpost.

## 1st Solution
From the boot menu. Select either the first or last option in the USB boot menu whichever works for you.

And in the installer in the "Drivers" section, do **NOT** select any GPU drivers at all! Again, select no GPU drivers otherwise you get a black screen. All should go well with no issues and you will be running on the "nouveau" drivers.

But if you really want to get GPU acceleration back you can now safely grab the nVidia drivers that do work, they are currently only on the AUR. So type the following commands in terminal to install them and get back to normalcy.

_Remove Current Driver:_
`sudo pacman -R xf86-video-nouveau`

_Install Legacy Driver:_
`paru -S nvidia-470xx-dkms nvidia-470xx-settings nvidia-470xx-utils`

_Install Legacy Libs:_
`paru -S lib32-nvidia-470xx-utils lib32-opencl-nvidia-470xx opencl-nvidia-470xx`

## Reboot

If this solution didn't work for you, proceed on reading the 2nd solution in XeroLinux's blogpost

**Comment by KingDutchIsBad** [comment]
Thank you for your help!
 I had done exactly this when installing axyl-os my issue was about having a option in the installer so that it is a little easier to install the OS. I wasn't able to proceed properly when I was installing axyl-os due to the next button getting hidden when confirming my options. I had fixed the issue by do some messing around with resizing the window and then getting the next button unhidden but it wasn't that great of a experience so I am merely suggesting adding an option to boot from legacy drivers as that will improve the live iso experience for some people.

**Comment by Kungger-git** [comment]
Unfortunately, there is no other method for me to add the legacy drivers in the package repository, because Github cannot host packages that are larger than 100mb.

Before it's asked, no we cannot control which driver gets included on the ISO or the installer. We are sorry on behalf of nVidia. They deserve the middle finger Linus Torvalds gave them.

**Comment by KingDutchIsBad** [comment]
They really do
