### ISSUE TITLE
LSP Neovim language servers and delete all configs for Neovim

### ISSUE THREAD

**Issue by Olavq** [axyl-os/axyl-iso#28]
First question is how can I configure language servers for LSP in config, which is default? I try to configure it by myself, but nothing works.  I don't understand where I should put language configuration and commands with default values.
The second question is what I must do to delete all configs and plugins which are supplied with the system if I want to configure it from scratch.

**Comment by abdoulayegk** [comment]
1. I was trying to do the same however it works fine the only problem that I notice was that I couldn't remove vim I only wanted to use neovim.

2. The solution to your problem is this rename the nvim file that you have in ~/.config to nvim.old or nvim.backup then create your now nvim folder and continue with your configuration it will work fine.
I noticed also when I backup the .vim folder and the vimrc file it's behaves very badly.

**Comment by Shinyzenith** [comment]
No reply from author, closing as stale.
