### ISSUE TITLE
Error when update base-devel for all wm

### ISSUE THREAD

**Issue by mariejie** [axyl-os/axyl-iso#64]
After I finish installing, then reboot, the first thing i do is update base-devel `sudo pacman -S --needed base-devel`, after finish update, keyboard freeze, can't spawn new terminal or open dmenu...
I'm try to reboot it 3-4 times, but everything is blank, nothing shows up, keyboard died.
WM: i3, bspwm, maybe all wm 👍 
![20220313_095939](https://user-images.githubusercontent.com/83217673/158043087-61498233-2494-4c40-a843-b35d7cd3ba9c.jpg)

##### My english not good :+1:

**Comment by thyeun** [comment]
@mariejie you should not using `paru -S --needed base-devel`, because Axyl-iso already is a custom make, it been choose some of the related package for the Axyl-iso, it might be crush your system, what you need to do after install is just execute `paru -Syu`, all the related `base-devel` will included.

im try out all WM it fine to run it, but i choose i3, easy to manage :) 

As you can see from the picture below
![Screenshot_2022-03-13-09-38-17_1366x768](https://user-images.githubusercontent.com/1939446/158062150-1ef71a17-b9b6-4ae5-aec3-7766ac5ebb1a.png)

**Comment by mariejie** [comment]
@thyeun omg thanks dude 😻
