### ISSUE TITLE
Unable to access windows file system

### ISSUE THREAD

**Issue by ksharinarayanan** [axyl-os/axyl-iso#9]
First of all, great work with the OS and ricing :)

I am unable to access the windows file system. This happens only with this OS. 

Any workarounds?

**Comment by angelofallars** [comment]
What is the message that appears when you try to mount the Windows partition with the `mount` command?

**Comment by ksharinarayanan** [comment]
I am not familiar with how to mount using a command line. I usually expect the partitions to appear in a graphical file manager like thunar.

**Comment by angelofallars** [comment]
Like Arch-based distros by default, Axyl does not automatically mount other partitions in the filesystem. That's why you can't see the Windows partition in Thunar.

Try launching a terminal with Super + Enter, and enter this command to check your partitions:
```bash
sudo fdisk -l
```

Note which Device (starts with `/dev/sda` on the left) has a type `Microsoft basic data`. That is the Windows filesystem.

Once you have found it (could be `dev/sda3` or `dev/sda2`, but check to be sure), run this command:
```bash
sudo mount (the Windows filesystem name) /mnt
```

To mount `/dev/sda2` for example:
```bash
sudo mount /dev/sda2 /mnt
```

After that, you can find the Windows filesystem by going to `/mnt` in Thunar.

**Comment by ksharinarayanan** [comment]
Woah, thanks! 😄

**Comment by angelofallars** [comment]
> Woah, thanks! smile

Glad I am able to help! 😊

**Comment by Kungger-git** [comment]
Since this issue has been solved, I'll close this now.
